### ISSUE TITLE
[BUG]: GameDB - Karaoke Revolution Love&Ballad / Night Selection Metadata Mixed

### ISSUE THREAD

**Issue by JWatersMeet** [PCSX2/pcsx2#10959]
### Describe the Bug

In the GameDB, it appears that the metadata for two Karaoke Revolution titles is partially mixed:

```
SLPM-62382:
  name: カラオケレボリューション ナイトセレクション2003
  name-sort: からおけれぼりゅーしょん ないとせれくしょん2003
  name-en: "Karaoke Revolution - Love & Ballad"
  region: "NTSC-J"
  compat: 4
SLPM-62383:
  name: カラオケレボリューション Love&Ballad
  name-sort: からおけれぼりゅーしょん Love&Ballad
  name-en: "Karaoke Revolution - Night Selection 2003"
  region: "NTSC-J"
```
To confirm (https://psxdatacenter.com/psx2/jlist2.html):
- SLPM-62382 is Love & Ballad
- SLPM-62383 is Night Selection

i.e. the English name is correct, but the Japanese name and name sort are swapped.

### Reproduction Steps

N/A

### PCSX2 Revision

v1.7.5630

### Operating System

Windows 11
