### ISSUE TITLE
[BUG]: Memory Card Folder wonkiness.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#11537]
### Describe the Bug

Update: Just scroll down to my last comment for TLDR.

PCSX2 currently does not take into account at all that PS2 uses UTC+9 timestamps. (Well actually it seems to be +9 from whatever the bios time is set to. PCSX2 seems to default bios to UTC time which is sensible.)
This results in the **Unix time in the index files is 9 hours into the future**, it is converted back again though so it is displayed correctly in bios.
However it results in some strange timestamps when converting back and forth between file and folder type.
Also note that converting **Folder MC -> File MC reverses the file order** and **rootdir timestamps are set to all zero bytes**.
Check my log below for more details.

### Reproduction Steps

1. Check current unix time.
2. Create memory card folder.
3. Copy a save to it.
4. Compare the unix time you noted and the unix time in the index file.
Also convert back and forth and notice the file order reversing.

### Expected Behavior

PS2 timestamps should be interpreted correctly and stored as an accurate Unix time, and converted back again to ps2 format correctly.

In my own program i simply do something like this:
```
void unix_to_jst(const time_t unixtime, struct tm *jst) {
    memset(jst, 0, sizeof(struct tm));
    const time_t adjusted_time = unixtime + 9 * 3600;
    gmtime_r(&adjusted_time, jst);
}

time_t jst_to_unix(struct tm *jst) {
    return timegm(jst) - 9 * 3600;
}
```
What about DST you may ask. Neither UTC nor JST (UTC+9) uses DST, they're always 9 hours apart. Once it has been converted to unix time you can do what you want with it, display it as UTC or local time or whatever.
I noticed the code once had something similar to this, but I think it maybe only converted forward, not back again.

### PCSX2 Revision

v1.7.5976

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### Logs & Dumps

Output from my own program below.
File MC timestamps are interpreted as UTC+9 (since that is how PS2 stores them) and displayed as UTC. (Meaning simply -9 hours from raw card date)
Folder MC timestamps simply converts the unix time from the index file to UTC.
pcsx2 stores the unix time in index files as +9 hours into the future for some reason. (Interprets the PS2 date (UTC+9) as if it was UTC). It is converted back correctly when read so it displays correctly in bios anyway.
Actual Unix time around the same time (after) as tests: 1720773629

Sample regular memory card file (everything is correct):
```
perm attr  created		modified		path
drwx e---- 2024-07-12 08:38:56	2024-07-12 08:39:06	/. (1 items, 2 KiB allocated)
drwx e---- 2024-07-12 08:39:06	2024-07-12 08:39:08		/BASLUS-21075HG (3 items, 3 KiB allocated)
-rwx e---- 2024-07-12 08:39:06	2024-07-12 08:39:07			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
-rwx e---- 2024-07-12 08:39:07	2024-07-12 08:39:07			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-12 08:39:08	2024-07-12 08:39:08			/icon.sys (964 bytes, 1 KiB allocated)
```

Memory card folder:
All of the unix times stored in index files are +9 hours into the future.
```
$ROOT:
  timeCreated: 1720805900
  timeModified: 1720805902
'BASLUS-21075HG\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00':
  order: 1
  timeCreated: 1720805900
  timeModified: 1720805901
icon00.ico\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 2
  timeCreated: 1720805901
  timeModified: 1720805902
icon.sys\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 3
  timeCreated: 1720805902
  timeModified: 1720805902
```
Ignore rootdir timestamps for Folders MC, they're generated by my program at runtime.
Timestamps on Folder MC are 9 hours into the future because of the unix time stored by pcsx2 in index files.
```
perm attr  created		modified		path
drwx e---- 2024-07-12 09:26:05	2024-07-12 09:26:05	/. (1 items, 2 KiB allocated) 
drwx e---- 2024-07-12 17:38:20	2024-07-12 17:38:22		/BASLUS-21075HG (3 items, 3 KiB allocated) 
-rwx e---- 2024-07-12 17:38:20	2024-07-12 17:38:21			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
-rwx e---- 2024-07-12 17:38:21	2024-07-12 17:38:22			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-12 17:38:22	2024-07-12 17:38:22			/icon.sys (964 bytes, 1 KiB allocated)
```

converted to file:
PCSX2 sets rootdir timestamps to all zero bytes when converting FolderMC -> File MC, displayed as 1899-12-30 15:00:00 here, why not simply generate a rootdir time from current time instead?
On conversion to File MC, save dirs gets -9 hours from the unix time which results in the correct time again.
Files gets -9 hours from the accurate date though. (-18 from the unix time stored)
Note that the file order has been reversed.
Also every time it is converted to file some extra time is added to file timestamps, 2-3 seconds here. (Don't know what's going on maybe it's based on current time when converted or something)
```
perm attr  created		modified		path
drwx e---- 1899-12-30 15:00:00	1899-12-30 15:00:00	/. (1 items, 2 KiB allocated) 
drwx e---- 2024-07-12 08:38:20	2024-07-12 08:38:22		/BASLUS-21075HG (3 items, 3 KiB allocated) 
-rwx e---- 2024-07-11 23:38:24	2024-07-11 23:38:24			/icon.sys (964 bytes, 1 KiB allocated) 
-rwx e---- 2024-07-11 23:38:24	2024-07-11 23:38:24			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-11 23:38:24	2024-07-11 23:38:24			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
```

converted back to folder:
```
$ROOT:
  timeCreated: 1720805900
  timeModified: 1720805902
icon.sys\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 1
  timeCreated: 1720773504
  timeModified: 1720773504
icon00.ico\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 2
  timeCreated: 1720773504
  timeModified: 1720773504
'BASLUS-21075HG\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00':
  order: 3
  timeCreated: 1720773504
  timeModified: 1720773504
```
Ignore rootdir timestamps for Folders MC, they're generated by my program at runtime.
```
perm attr  created		modified		path
drwx e---- 2024-07-12 09:26:23	2024-07-12 09:26:23	/. (1 items, 2 KiB allocated) 
drwx e---- 2024-07-12 17:38:20	2024-07-12 17:38:22		/BASLUS-21075HG (3 items, 3 KiB allocated)
-rwx e---- 2024-07-12 08:38:24	2024-07-12 08:38:24			/icon.sys (964 bytes, 1 KiB allocated)
-rwx e---- 2024-07-12 08:38:24	2024-07-12 08:38:24			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-12 08:38:24	2024-07-12 08:38:24			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
```

converted back to file again:
67 extra seconds added to file timestamps for some reason. (Maybe has to do with when it was converted or something.)
```
perm attr  created		modified		path
drwx e---- 1899-12-30 15:00:00	1899-12-30 15:00:00	/. (1 items, 2 KiB allocated) 
drwx e---- 2024-07-12 08:38:20	2024-07-12 08:38:22		/BASLUS-21075HG (3 items, 3 KiB allocated)
-rwx e---- 2024-07-11 23:39:33	2024-07-11 23:39:33			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
-rwx e---- 2024-07-11 23:39:33	2024-07-11 23:39:33			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-11 23:39:33	2024-07-11 23:39:33			/icon.sys (964 bytes, 1 KiB allocated)
```

converted back to folder again:
```
$ROOT:
  timeCreated: 1720805900
  timeModified: 1720805902
'BASLUS-21075HG\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00':
  order: 1
  timeCreated: 1720773573
  timeModified: 1720773573
icon00.ico\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 2
  timeCreated: 1720773573
  timeModified: 1720773573
icon.sys\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00:
  order: 3
  timeCreated: 1720773573
  timeModified: 1720773573
```
```
perm attr  created		modified		path
drwx e---- 2024-07-12 09:28:23	2024-07-12 09:28:23	/. (1 items, 2 KiB allocated)
drwx e---- 2024-07-12 17:38:20	2024-07-12 17:38:22		/BASLUS-21075HG (3 items, 3 KiB allocated)
-rwx e---- 2024-07-12 08:39:33	2024-07-12 08:39:33			/BASLUS-21075HG (77168 bytes, 76 KiB allocated)
-rwx e---- 2024-07-12 08:39:33	2024-07-12 08:39:33			/icon00.ico (118616 bytes, 116 KiB allocated)
-rwx e---- 2024-07-12 08:39:33	2024-07-12 08:39:33			/icon.sys (964 bytes, 1 KiB allocated)
```
