### ISSUE TITLE
Memcard Folder Not Loading for Shadow of the Colossus Japanese Version (SCPS-15097)

### ISSUE THREAD

**Issue by SpiralCut** [PCSX2/pcsx2#3616]
***PCSX2 version:***
``(For example, stable build v1.6.0 (or) development builds v1.7.0-dev-xxx)``
Dev Build PCSX2 1.7.0-20200811005056

- **Notes**:
(None

***PCSX2 options:***
``(For example, Clamping/Rounding, Speedhacks, GameFixes)``
Set at Preset Safe (Default)

***Plugins used:***
GSdx32-AVX2.dll [GSdx 20200811005056 (MSVC 19.26 AVX2/AVX2) 1.2.0]
LilyPad.dll [LilyPad (20200811005056) 0.12.1]
Spu2-X.dll [SPU2-X 20200811005056 2.0.0]
cdvdGigaherz.dll [cdvdGigaherz 20200811005056 0.11.0]
USBnull.dll [USBnull Driver 20200811005056 0.7.0]
FWnull.dll [FWnull Driver 20200811005056 0.7.0]
DEV9null.dll [DEV9null Driver 20200811005056 0.5.0]

***Description of the issue:***
Shadow of the Colossus Japanese edition (SCPS-15097) does not load save files when loaded from a memcard folder.  I am able to load the save when it is included in an actual .ps2 memcard file, but when I convert that same file to folder the save does not load.

***How to reproduce the issue:***
1) Insert Shadow of the Colossus.ps2 (included with ticket) into memcard slot 1 and boot SCPS-15097 and the game should show two save files available
2) Convert Shadow of the Colossus.ps2 to a memcard folder through the PCSX2 memcard manager and insert that memcard folder into memcard slot 1 and boot SCPS-15097 and now the game will not show any save files

*Notes:
-I thought maybe it was a bad rip due to the filetype of the ISO I used (.cdr) since PCSX2 was not showing a crc but I have the same results (both no save loaded and missing crc) after both ripping my disc to iso and booting directly from the actual disc using the cdvdGigaherz plugin so I don't think it's related.
-Save comes from a real PS2 playstation that was converted to PS3 and then migrated to PC.

***Last known version to work:***
Unknown, this is my first time trying memcard folders

***PC specifications:***
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``
Intel(R) Core(TM) i7-8700K
 CPU @ 3.70GHz
Windows 10 Pro 64 Bit English (18363)
Asus GTX 1070TI

[Shadow of the Colossus.zip](https://github.com/PCSX2/pcsx2/files/5109134/Shadow.of.the.Colossus.zip)
[PCSX2_log_(Folder).txt](https://github.com/PCSX2/pcsx2/files/5109141/PCSX2_log_.Folder.txt)
[PCSX2_log_(Memcard).txt](https://github.com/PCSX2/pcsx2/files/5109142/PCSX2_log_.Memcard.txt)

**Comment by MrCK1** [comment]
@SpiralCut by any chance, is the issue affected by creating a fresh folder memory card and trying to save/load from that?

**Comment by SpiralCut** [comment]
@MrCK1 
No, I tried removing the save itself and trying to create a new save in game using a folder I know works for other ps2 saves.  The game will say it saved successfully but the save won’t show up when you try to load.

**Comment by refractionpcsx2** [comment]
Is this still an issue (if using a new save)?

**Comment by SpiralCut** [comment]
Yes, I just tried it using SCPS-15097 and this time it crashed when trying to save for the first time.  I'm not sure what the files are to upload for the latest versions of PCSX2 but I think I've included the log with this post.

By the way, this is on 1.7.2731 (latest nightly as of 5/10) on the x64 avx2 build
[emuLog.txt](https://github.com/PCSX2/pcsx2/files/8655874/emuLog.txt)

**Comment by Mrlinkwii** [comment]
how is this on nightly ?

**Comment by SpiralCut** [comment]
Issue still occurs on nightly (tested on windows v 1.7.4927) .  I tried both copying the save into my normal memory card folder and reconverting the .ps2 file for my original save (taken from a PS3 with the PS2 memory card adapter) to a new save card folder but it's still not reading the files

**Comment by refractionpcsx2** [comment]
any chance somebody could try this again with #10791 ?

**Comment by SpiralCut** [comment]
Not sure if 10791 is present in the latest nightly (1.7.5560) but I still have the issue with Shadow of the Colossus JP in 1.7.5560

**Comment by Goatman13** [comment]
It's not working because it is explicitly blocked in game database. Adding SCPS-15097 to memcardFilters fixed it.

```yaml
SCPS-15097:
  name: "ワンダと巨像"
  name-sort: "わんだときょぞう"
  name-en: "Wanda to Kyozou"
  region: "NTSC-J"
  compat: 5
  roundModes:
    eeRoundMode: 3 # Prevents Wander from moving when charging the floor.
  gsHWFixes:
    recommendedBlendingLevel: 4 # Fixes water color.
    halfPixelOffset: 5 # Fixes misalignments and borders on side.
    nativeScaling: 3 # Fixes post effects shadows and DOF effects.
  memcardFilters:
    - "SCAJ-20146"
    - "SCAJ-20196"
    - "SCAJ-20099"
    - "SCPS-11003"
    - "SCPS-19103"
    - "SCPS-19151"
    - "SCPS-55001"
```

Code reading serials (it's in more than 1 place):
```c
if (const GameDatabaseSchema::GameEntry* game = GameDatabase::findGame(s_disc_serial))
{
	memcardFilters = game->memcardFiltersAsString();
}

....

FileMcd_Reopen(memcardFilters.empty() ? s_disc_serial : memcardFilters);
```

From what i understand if filter is not empty it will use only ids from filter, ignoring disc id. I guess there will be more issues like that in gamedb and probably someone want to fix that in code not in database anyway. Ignoring disc id seems like a bug here.

I’m not confident enough to tinker with the memory card code, so no pull request from me :D

Edit: There are other entries like that in DB (just in case if db fix is preferred). SLUS-20627, SCPS-19317, SCPS-19320, SLPS-25060, SLPS-25061, SLPS-25366, probably more.
