### ISSUE TITLE
[BUG]: Appimage build of PCSX2 doesn't let user to select and run stuff on igpu at Prime system

### ISSUE THREAD

**Issue by Leopard1907** [PCSX2/pcsx2#5333]
### Describe the Bug

Bug is basically, on Appimage build both Vulkan and OpenGL backends are unable to run anything on igpu. They default to dgpu.

Appimage builds obtained from:

https://github.com/PCSX2/pcsx2/tags

On gpu selection section of Vulkan backend , gpu listed as "Default Adapter" and it is skipped despite it is selected:

```
GPU 0: NVIDIA GeForce GTX 1050
Requested GPU 'Default Adapter' not found, using first (NVIDIA GeForce GTX 1050)
3 vulkan queue families
[2022-01-12 22:27:28.713] [MANGOHUD] [info] [overlay.cpp:705] Uploading is disabled (permit_upload = 0)
VK_EXT_provoking_vertex is supported
Read 79 entries from '/home/asus/pcsx2-v1.7.2225-linux-AppImage-64bit.AppImage.config/PCSX2/cache/vulkan_shaders.idx'
Using hardware for point expansion and hardware for line expansion.
```

When i force my Intel igpu to be only visible VLK implementation with using:

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=mesa VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/intel_icd.x86_64.json
```
it throws 

```
(CreateVulkanInstance) vkCreateInstance failed:  (-9: VK_ERROR_INCOMPATIBLE_DRIVER)
```

Aur-git package ( https://aur.archlinux.org/packages/pcsx2-git/ ) works correctly and lists both gpu's correctly.

![Screenshot_20220113_153953](https://user-images.githubusercontent.com/24878978/149337176-51a44e5f-2557-41bf-aeef-6bc430a2b0d6.png)

System info:

```
Graphics:
  Device-1: Intel HD Graphics 630 vendor: ASUSTeK driver: i915 v: kernel
    bus-ID: 00:02.0 chip-ID: 8086:591b
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] vendor: ASUSTeK
    driver: nvidia v: 510.39.01 bus-ID: 01:00.0 chip-ID: 10de:1c8d
  Device-3: Realtek USB2.0 HD UVC WebCam type: USB driver: uvcvideo
    bus-ID: 1-6:3 chip-ID: 0bda:57f5
  Display: x11 server: X.Org 1.21.1.3 compositor: kwin_x11 driver:
    loaded: intel,nvidia unloaded: fbdev,modesetting,vesa alternate: nouveau,nv
    resolution: 1920x1080~60Hz s-dpi: 96
  OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 21.3.3
    direct render: Yes
```

Normally, gpu 0 is Intel igpu and gpu 1is NV dgpu.

### Reproduction Steps

Use PCSX2 Appimage builds on a dual gpu (Optimus/Prime) and see how it ignores one of them (in my case igpu).

On AUR pcsx2-git build both igou and dgpu are recognized and works correctly.

### Expected Behavior

Appimage build behaving like AUR build.

As an extra note: RPCS3 Appimage builds doesn't have such issue. So it is likely a misconfig on how PCSX2 builds Appimages.

### PCSX2 Revision

v1.7.2232 ( also reproducible with older builds )

### Operating System

Linux (64bit) - Specify Distro Below

### If Linux - Specify Distro

EndavourOS ( Arch based )
