### ISSUE TITLE
[BUG]: Sly 3: Honor Among Thieves - VU Clamping set to "Extra + Preserve Sign" fixes a broken level but breaks shadow rendering

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [PCSX2/pcsx2#7241]
### Describe the Bug

This was brought to my attention very recently by user @Logics4.  If you have "Game Fixes" enabled in the "Advanced System" tab of any release of Sly 3, whether it's NTSC-U, PAL, or NTSC-K, character shadows will still work as expected but environment shadows will act very glitchy, rendering through other buildings, and partially popping in and out of existence.  However, if this option is disabled, both environment and character shadows act like they should.

Short video clip of shadows with "Game Fixes" enabled:

https://user-images.githubusercontent.com/58268914/196756117-8c7f65b3-9346-4aae-a0cb-f001cec7c8f9.mp4

Short video clip of shadows with "Game Fixes" disabled:

https://user-images.githubusercontent.com/58268914/196756208-2eb01821-bfda-413d-b972-a41c2fa12f39.mp4

This has been replicated across my computer and the computer of user, @Logics4.  I'll add both our CPUs and GPUs to issue.

### Reproduction Steps

1.  Edit the custom profile of any release of Sly 3.
2.  Make sure "Game Fixes" is enabled.
3.  Go ingame.

### Expected Behavior

Environment shadows should stay rendered at all times, not clip through buildings, or disappear based on camera angle.

### PCSX2 Revision

v1.7.3461

### Operating System

Windows 10 (64bit)

### CPU

Intel Core i9-10900K (Me), AMD Ryzen 7 5800H (Logics4)

### GPU

NVIDIA RTX 2080 Super (Me), NVIDIA GeForce RTX 3060 (Logics4)

**Comment by GN876** [comment]
I tested this game last week, the camera in the level The Ancestors' Gauntlet is broken without gamefixes. VU clamping needs to be on either extra or extra + preserve sign. In my testing, extra + preserve has better performance. Seems that the rest of the game works fine with VU clamping on normal.

https://forums.pcsx2.net/Thread-Bug-Report-Sly-3-Honor-Among-Thieves-NTSC-U

**Comment by refractionpcsx2** [comment]
why didn't you check that when you added the fixes 17 days ago? https://github.com/PCSX2/pcsx2/pull/7121/files

**Comment by refractionpcsx2** [comment]
![image](https://user-images.githubusercontent.com/6278726/196764065-12e4ba4b-9b18-4799-8af4-008a3cec8c8a.png)

**Comment by Logics4** [comment]
> why didn't you check that when you added the fixes 17 days ago? #7121

So I tested a bit more, and
```yaml
SCUS-97464:
  name: "Sly 3 - Honor Among Thieves"
  region: "NTSC-U"
  compat: 5
  roundModes:
    vuRoundMode: 0 # Fixes game engine issue with bombs and ladders.
  clampModes:
    vuClampMode: 2 # Fixes bugged camera.
  gsHWFixes:
    halfPixelOffset: 2 # Fixes chromatic effect.
```
commenting out `vmClampMode` seems to fix the shadows.
