### ISSUE TITLE
[Feature Request]: Please add the previous games to the GameDB memcardFilters for the Ratchet series.

### ISSUE THREAD

**Issue by kevin98761234** [PCSX2/pcsx2#8406]
### Description

Ratchet & Clank 2 Going Commando allows you to load the saved data of the first title.
Ratchet & Clank 3 Up Your Arsenal allows you to load the saved data of the first and second titles.

### Reason

The linkage activation of the saved data is enabled in the game.

### Examples

```
SCPS-19317:
  name: "Ratchet & Clank 2 - Going Commando [PlayStation 2 The Best]"
  region: "NTSC-J"
  gameFixes:
    - EETimingHack # Fixes SPR errors while going in-game.
  gsHWFixes:
    mipmap: 1
    autoFlush: 1
  memcardFilters:
    - "SCAJ-20001"
    - "SCPS-15037"
    - "SCPS-19211"
    - "SCPS-19310"
    - "SCPS-19316"
```
