### ISSUE TITLE
Battlefield 2 - Modern combat 2 - 2e Flickering bug (v1.7.3998)

### ISSUE THREAD

**Issue by IamLupo** [PCSX2/pcsx2#8870]
### Describe the Bug

The bug consist of heavy flickering graphics issues that happends for Battlefield 2 Modern Combat in multiplayer mode. This starts to happen for any hardware as renderer. Software renderer does work correctly without flickering! Our discord community all confirms they experience the same issue thats why i jumped in for investigation and a solution.

The flickering issues I manage to track down by testing version 1.7.3997 that has not the flickering issue. The version v1.7.3998 has the flickering issue.
By checking the version v1.7.3998 we can find the following pull https://github.com/PCSX2/pcsx2/pull/7990.

My investigation started to reverse the code changes line by line , until i stumbled to the code that started to cause to the problem. (GSRendererHW.cpp line [224-226](https://github.com/PCSX2/pcsx2/pull/7990/files#diff-a5cfae1bda69d50c81cd056255b5c6f3e26cdb0877afceb72953214592f1b1aeR224)).
You see that the code:
```c++
m_tc->IncAge();
```
Got switched to the top before GSRenderer::VSync got executed. I basically switch it back to the bottom and this caused that the game didn't have the heavy flickering anymore.

I messaged on the pull and @refractionpcsx2 [responded](https://github.com/PCSX2/pcsx2/pull/7990#issuecomment-1550902283) that this is better be solved by GSDump then a reverse of this code change.

### Reproduction Steps

- Change settings:
    Graphic:
    Renderer: Direct3D 12
    Adapter: RTX 3080
    Network & HDD
    Enable network
    Ethernet device Type: Sockets
    Ethernet device: Ethernet

- Start the game, click in the main menu: Play online
- Create a new adapter with DNS IP(45.7.228.197).
- Login with your account or your create one.
- Join a random server

Once you joined the game the flickering starts happening.

### PCSX2 Revision

v1.7.3998

### Operating System

Windows 10 (64bit)

### CPU

AMD Ryzen 9 5900X

### GPU

RTX 3080

### GS Settings

```
SLUS-21026:
  name: "Battlefield 2 - Modern Combat"
  region: "NTSC-U"
  compat: 5
  gsHWFixes:
    autoFlush: 1 # Post-processing.
    halfPixelOffset: 2 # Offset post-processing.
    texturePreloading: 1 # Spikes all over the place otherwise.
    textureInsideRT: 1 # Fixes light shinging through objects.
    cpuCLUTRender: 1 # Fixes light shining through objects.
    getSkipCount: "GSC_Battlefield2" # Depth clear.
    beforeDraw: "OI_Battlefield2" # Framebuffer copy, fixes rendering for bottom part of screen.
```
 
Keep in mind the [1e Flickering bug](https://github.com/PCSX2/pcsx2/issues/8869) i fixed already with the "bool GSHwHack::OI_Battlefield2MP" patch.

### Emulation Settings

![settings](https://github.com/PCSX2/pcsx2/assets/8842375/fcfb8675-85de-4d20-90b4-86664015740a)

### GS Window Screenshots

![InGame](https://github.com/PCSX2/pcsx2/assets/8842375/4910e10c-26f9-4bbe-829a-f0dd8bf834ef)
You cant see the flickering in the screenshot. On the top he has drawn the correct way it should be. Its basically drawing not the full screen. Because of this The skybox is heavily glitching and is not even full rendered. Until half the screen.
If i look into the direction of the sun it is even really heavily flickering.

### Logs & Dumps

![Battlefield 2 - Modern Combat_SLUS-21026_20230517133523](https://github.com/PCSX2/pcsx2/assets/8842375/87a01e9a-5ae3-4a67-a62c-23d0e676b4bb)

GSdump: [Battlefield 2 - Modern Combat_SLUS-21026_20230517133523.gs.zst](https://mega.nz/file/4YpxWIAK#usguDGuv0-UGJ-Ujrs4YitTZBEnPzhrxagMKYoS3u6s)
